import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'John',
      email: 'admin@exzmple.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@exzmple.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'ARTICULATED BLACK',
      slug: 'ARTICULATED-BLACK-NAIRO',
      category: 'ARTICULATED FLIES',
      image: '/images/1.jpg',
      price: 5.0,
      brand: 'ARTICULATED FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'ARTICULATED BROWN',
      slug: 'ARTICULATED-BROWN-NAIRO',
      category: 'ARTICULATED FLIES',
      image: '/images/2.jpg',
      price: 5.0,
      brand: 'ARTICULATED FLIES',
      rating: 8.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'SEX DUNGEON BLACK (VARIANT) ',
      slug: 'SEX-DUNGEON-BLACK-NAIRO ',
      category: 'ARTICULATED FLIES',
      image: '/images/3.jpg',
      price: 5.0,
      brand: 'ARTICULATED FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'ARTICULATED GRAY',
      slug: 'ARTICULATED-GRAY-NAIRO',
      category: 'ARTICULATED FLIES',
      image: '/images/4.jpg',
      price: 5.0,
      brand: 'ARTICULATED FLIES',
      rating: 8.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'RED EYED OLIVE',
      slug: 'RED-EYED-OLIVE-NAIRO',
      category: 'ARTICULATED FLIES',
      image: '/images/5.jpg',
      price: 5.0,
      brand: 'ARTICULATED FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'ARTICULATED WHITE',
      slug: 'ARTICULATED-WHITE-NAIRO',
      category: 'ARTICULATED FLIES',
      image: '/images/6.jpg',
      price: 5.0,
      brand: 'ARTICULATED FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'RED EYED BLACK YELLOW',
      slug: 'RED-EYED-BLACK-YELLOW-NAIRO',
      category: 'ARTICULATED FLIES',
      image: '/images/7.jpg',
      price: 5.0,
      brand: 'ARTICULATED FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'ARTICULATED OLIVE CARP',
      slug: 'ARTICULATED-OLIVE-CARP',
      category: 'ARTICULATED FLIES',
      image: '/images/8.jpg',
      price: 5.0,
      brand: 'ARTICULATED FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'ARTICULATED PRINCE',
      slug: 'ARTICULATED-PRINCE-NAIRO',
      category: 'ARTICULATED FLIES',
      image: '/images/9.jpg',
      price: 5.0,
      brand: 'ARTICULATED FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'ARTICULATED YELLOW CARP',
      slug: 'ARTICULATED-YELLOW-CARP-NAIRO',
      category: 'ARTICULATED FLIES',
      image: '/images/10.jpg',
      price: 5.0,
      brand: 'ARTICULATED FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'YELLOW BROWN STREAMER',
      slug: 'YELLOW BROWN STREAMER-NAIRO',
      category: 'ARTICULATED FLIES',
      image: '/images/11.jpg',
      price: 5.0,
      brand: 'ARTICULATED FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'ORANGE HEAD STREAMER',
      slug: 'ORANGE-HEAD-STREAMER-NAIRO',
      category: 'ARTICULATED FLIES',
      image: '/images/12.jpg',
      price: 5.0,
      brand: 'ARTICULATED FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'RED EYED PURPLE',
      slug: 'RED-EYED-PURPLE-NAIRO',
      category: 'ARTICULATED FLIES',
      image: '/images/13.jpg',
      price: 5.0,
      brand: 'ARTICULATED FLIES',
      rating: 8.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'ARTICULATED OLIVE',
      slug: 'ARTICULATED-OLIVE-NAIRO',
      category: 'ARTICULATED FLIES',
      image: '/images/14.jpg',
      price: 5.0,
      brand: 'ARTICULATED FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'RED EYED BROWN YELLOW ARTICULATED',
      slug: 'RED-BROWN-YELLOW-ARTICULATED',
      category: 'ARTICULATED FLIES',
      image: '/images/15.jpg',
      price: 5.0,
      brand: 'ARTICULATED FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'BLUE DUN',
      slug: 'BLUE-DUN-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/16.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'ELK CADDIS TAN',
      slug: 'ELK-CADDIS-TAN-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/17.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'ADAMS PARACHUTE',
      slug: 'ADAMS-PARACHUTE-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/18.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'CURMUDGEON CRUMPLER',
      slug: 'CURMDGEON-CRUMPLER-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/19.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'ADAMS',
      slug: 'ADANS-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/20.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'BLACK ANT',
      slug: 'BLACK-ANT-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/21.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'DOUBLE RENEGADE',
      slug: 'DOUBLE-RENEGADE-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/22.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'ROYAL HUMPHY',
      slug: 'ROYAL-HUMPHY-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/23.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'DADS FAVOURITE',
      slug: 'DADS-FAVOURITE-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/24.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'ROYAL WULFF WHITE TAIL',
      slug: 'ROYAL-WULFF-WHITE-TAIL-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/25.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'DADDY LONGLEGS',
      slug: 'DADDY-LONGLEGS-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/26.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },

    {
      name: 'BLACK GNAT PARACHUTE',
      slug: 'BLACK-GNAT-PARACHUTE-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/27.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'ELK CADDIS YELLOW',
      slug: 'ELK-CADDIS-YELLOW-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/28.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'PURPLE HAZE(YELLOW POST)',
      slug: 'PURPLE-HAZE-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/29.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'EDS BLACK ANT',
      slug: 'EDS-BLACK-ANT-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/30.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'BLACK BEETLE EMERGER',
      slug: 'BLACK-BETTLE-EMERGER-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/31.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'STRIKING CADDIS',
      slug: 'STRIKING-CADDIS-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/32.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'DAVES HOPPER OLIVE',
      slug: 'DAVES-HOPPER-OLIVE-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/33.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'OCTOBER IRRESISTABLE CADDIS',
      slug: 'OCTOBER-IRRESISTABLE-CADDIS-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/34.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'ROYAL COACHMAN',
      slug: 'ROYAL-COACHMAN-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/35.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'TENT WING',
      slug: 'TENT-WING-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/36.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'KLINKHAMMER INDICATOR',
      slug: 'KLINKHAMMER-INDICATOR-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/37.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'PEACOCK & HERL',
      slug: 'PEACOCK-HERL-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/38.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'YELLOW HUMPHY',
      slug: 'YELLOW-HUMPHY-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/39.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'BLACK MIDGE',
      slug: 'BLACK-MIDGE-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/40.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'BLACK CADDIS',
      slug: 'BLACK-CADDIS-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/41.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'MORGAN MAHOGANY',
      slug: 'MORGAN-MAHOGANY-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/42.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'MARCH BROWN DRY FLY',
      slug: 'MARCH-BROWN-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/43.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'HENRYVILLE SPECIAL',
      slug: 'HENRYVILLE-SPECIAL-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/44.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'LIGHT HENDRICKSON',
      slug: 'LIGHT-HENDRICKSON-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/45.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'RED ANT',
      slug: 'RED-ANT-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/46.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'POPCORN BEETLE',
      slug: 'POPCORN-BEETLE-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/47.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'GYPSY KING',
      slug: 'GYPSY-KING-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/48.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'SUSPENDED BEETLE',
      slug: 'SUSPENDED-BEETLE-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/49.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'ADAMS FEMALE',
      slug: 'ADAMS-FEMALE-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/50.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'XFACTOR PEACOCK',
      slug: 'XFACTOR-PEACOCK-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/51.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'KAKAHI QUEEN',
      slug: 'KAKAHI-QUEEN-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/52.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'XFACTOR OLIVE',
      slug: 'XFACTOR-OLIVE-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/53.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'MOSQUITO',
      slug: 'MOSQUITO-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/54.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'DRY HACKLE RED FEMALE',
      slug: 'DRY-HACKLE-RED-FEMALE-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/55.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'PALMER BROWN',
      slug: 'PALMER-BROWN-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/56.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'RED HUMPHY',
      slug: 'RED-HUMPHY-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/57.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'ROYAL COACHMAN PARACHUTE',
      slug: 'ROYAL-COACHMAN-PARACHUTE-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/58.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'CAPTAIN',
      slug: 'CAPTAIN-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/59.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'BROWN HACKLE PEACOCK',
      slug: 'BROOWN-HACKLE-PEACOCK-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/60.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'IRRESISTABLE ADAMS BLACK TAIL',
      slug: 'IRRESISTABLE-ADAMS-BLACK-TAIL-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/61.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'RUBBER LEGS ELK CADDIS TAN',
      slug: 'RUBBER-LEGS-ELK-CADDIS-TAN-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/62.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'BROWN CADDIS',
      slug: 'BROWN-CADDIS-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/63.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'GREEN DRAKE',
      slug: 'GREEN-DRAKE-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/64.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'BROWN WULFF',
      slug: 'BROWN-WULFF-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/65.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'BLACK GNAT PARACHUTE',
      slug: 'BLACK-GNAT1-PARACHUTE-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/66.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'BLUE UPRIGHT',
      slug: 'BLUE-UPRIGHT-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/67.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'KING OF WATERS',
      slug: 'KING-OF-WATERS-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/68.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'HI-VIS ADAMS PARACHUTE',
      slug: 'HI-VIS-ADAMS-PARACHUTE-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/69.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'HEADLIGHT SALLY',
      slug: 'HEADLIGHT-SALLY-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/70.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'QUEEN OF WATERS',
      slug: 'QUEEN-OF-WATERS-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/71.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'YELLOW CAHILL',
      slug: 'YELLOW-CAHILL-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/72.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'BUZZBALL',
      slug: 'BUZZBALL-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/73.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'KLINKHAMMER BLACK',
      slug: 'KLINKHAMMER-BLACK-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/74.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'HI-VIS GRIFFITH GNAT',
      slug: 'HI-VIS-GRIFFITH-GNAT-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/75.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'LOOP CADDIS',
      slug: 'LOOP-CADDIS-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/77.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'TOM THUMB',
      slug: 'TOM-THUMB-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/78.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'HOT WING ELK CADDIS OLIVE',
      slug: 'HOT-WING-ELK-CADDIS-OLIVE-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/79.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'FEMALE BEAVERKILL',
      slug: 'FEMALE-BEAVERKILL-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/80.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'BLACK GNAT',
      slug: 'BLACK-GNAT1-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/81.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'ADAMS OLIVE',
      slug: 'ADAMS-OLIVE-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/82.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'COCHY BONDDU',
      slug: 'COCHY-BONDDU-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/83.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'ROYAL WULLF CHARTREUSE POST',
      slug: 'ROYAL-WULLF-CHARTREUSE-POST-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/84.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'SULPHUR DUN',
      slug: 'SULPHUR-DUN-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/85.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'ADAMS CRIPPLE',
      slug: 'ADAMS-CRIPPLE-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/86.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'ADAMS PARAWULLF',
      slug: 'ADAMS-PARAWULLF-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/87.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'PSYCHO CADDIS BLACK',
      slug: 'PSYCHO-CADDIS-BLACK-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/88.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'BIBIO HOPPER',
      slug: 'BIBIO-HOPPER-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/89.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'ROYAL RENEGADE',
      slug: 'ROYAL-RENEGADE-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/90.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'BLACK RED FLYING ANT',
      slug: 'BLACK-RED-FLYING-ANT-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/91.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'YELLOW SALLY',
      slug: 'YELLOW-SALLY-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/92.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'OCTOBER CADDIS',
      slug: 'OCTOBER-CADDIS-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/93.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'WONDER-WINGS-ADAMS',
      slug: 'WONDER-WINGS-ADAMS-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/94.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'HI-VIS PARACHUTE CADDIS CHARTREUSE POST',
      slug: 'HI-VIS-PARACHUTE-CADDIS-CHARTREUSE-POST-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/95.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'BLACK PARACHUTE CADDIS',
      slug: 'BLACK-PARACHUTE-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/96.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'CLOWN SHOE BROWN',
      slug: 'CLOWN-CHOE-BROWN-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/97.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'DAVES HOPPER FOAM BODY',
      slug: 'DAVES-HOPPER-FOAM-BODY-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/98.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'HUMPHY ADAMS',
      slug: 'HUMPHY-ADAMS-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/99.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'PATRIOTIC DRY FLY',
      slug: 'PATRIOTIC-FLY-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/100.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'CADDIS DYRET',
      slug: 'CADDIS-DYRET-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/101.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'CREAM VARIENT',
      slug: 'CREAM-VARIENT-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/102.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'GREEN DRAKE GINGER',
      slug: 'GREEN-DRAKE-GINGER-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/103.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'GOLD RIB HARES EAR',
      slug: 'GOLD-RIB-HARES-EAR-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/104.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'JC HORNBERG',
      slug: 'JC-HORNBERG-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/105.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'HORNBERG DRY FLY',
      slug: 'HORNBERG-FLY-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/106.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'FIERY BROWN',
      slug: 'FIERY-BROWN-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/107.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'GRIFFITH GNAT',
      slug: 'GRIFFITH-GNAT-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/108.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'HI-VIS PARACHUTE CADDIS PINK POST',
      slug: 'HI-VIS-PARACHUTE-CADDIS-PINK-POST-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/109.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'PURPLE PARACHUTE(WHITE POST)',
      slug: 'PURPLE-PARACHUTE-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/110.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'WESTERN COACHMEN',
      slug: 'WESTERN-COACHMAN-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/111.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'IRRESISTABLE',
      slug: 'IRESISTABLE-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/76.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'ELK CADIS GRAY',
      slug: 'ELK-CADIS-GRAY-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/112.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'GRAY WULFF',
      slug: 'GRAY-WULFF-DRY-NAIRO',
      category: 'DRY FLIES',
      image: '/images/184.jpg',
      price: 3.5,
      brand: 'DRY FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'BLUE GILL CLOUSER',
      slug: 'BLUE-GILL-CLOUSER-SWATER-NAIRO',
      category: 'SALT WATER',
      image: '/images/114.jpg',
      price: 7.0,
      brand: 'SALT WATER FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'CHUM FLY',
      slug: 'CHUM-FLY-SWATER-NAIRO',
      category: 'SALT WATER',
      image: '/images/115.jpg',
      price: 7.0,
      brand: 'SALT WATER FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'WARMWATER PURPLE BLACK',
      slug: 'WARMWATER-PURPLE-BLACK-SWATER-NAIRO',
      category: 'SALT WATER',
      image: '/images/116.jpg',
      price: 7.0,
      brand: 'SALT WATER FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: ' CLOUSER MINNOW WHITE RED',
      slug: 'CLOUSER-MINNOW-WHITE-RED-SWATER-NAIRO',
      category: 'SALT WATER',
      image: '/images/117.jpg',
      price: 7.0,
      brand: 'SALT WATER FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'CRAZY CHARLIE PINK',
      slug: 'CRAZY-CHARLIE-PINK-SWATER-NAIRO',
      category: 'SALT WATER',
      image: '/images/118.jpg',
      price: 7.0,
      brand: 'SALT WATER FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'SPARKLE GRUB',
      slug: 'SPARKLE-GRUB-SWATER-NAIRO',
      category: 'SALT WATER',
      image: '/images/119.jpg',
      price: 7.0,
      brand: 'SALT WATER FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'PERMIT CRAB BROWN',
      slug: 'PERMIT-CRAB-BROWN-SWATER-NAIRO',
      category: 'SALT WATER',
      image: '/images/120.jpg',
      price: 7.0,
      brand: 'SALT WATER FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'F.O.D FLY',
      slug: 'FOD-FLY-SWATER-NAIRO',
      category: 'SALT WATER',
      image: '/images/121.jpg',
      price: 7.0,
      brand: 'SALT WATER FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'FLASH MINNOW',
      slug: 'FLASH-MINNOW-SWATER-NAIRO',
      category: 'SALT WATER',
      image: '/images/122.jpg',
      price: 7.0,
      brand: 'SALT WATER FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'MINI DIABLO CRAB',
      slug: 'MINI-DIABLO-CRAB-SWATER-NAIRO',
      category: 'SALT WATER',
      image: '/images/123.jpg',
      price: 7.0,
      brand: 'SALT WATER FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'MATURDA CRAB',
      slug: 'MATURDA-CRAB-SWATER-NAIRO',
      category: 'SALT WATER',
      image: '/images/124.jpg',
      price: 7.0,
      brand: 'SALT WATER FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'PERMIT CRAB ORANGE',
      slug: 'PERMIT-CRAB-ORANGE-SWATER-NAIRO',
      category: 'SALT WATER',
      image: '/images/125.jpg',
      price: 7.0,
      brand: 'SALT WATER FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'CRAZY CHARLIE TAN',
      slug: 'CRAZY-CHARLIE-TAN-SWATER-NAIRO',
      category: 'SALT WATER',
      image: '/images/126.jpg',
      price: 7.0,
      brand: 'SALT WATER FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'SHRIMP ORANGE',
      slug: 'SHRIMP-ORANGE-SWATER-NAIRO',
      category: 'SALT WATER',
      image: '/images/127.jpg',
      price: 7.0,
      brand: 'SALT WATER FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'BEAD HEAD  FLUFF BUTT CHARTREUSE BLACK',
      slug: 'BEAD-HEAD-BUTT-C-BLACK-SWATER-NAIRO',
      category: 'SALT WATER',
      image: '/images/128.jpg',
      price: 7.0,
      brand: 'SALT WATER FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'BONEFISH SLIDER',
      slug: 'BONEFISH-SLIDER-SWATER-NAIRO',
      category: 'SALT WATER',
      image: '/images/129.jpg',
      price: 7.0,
      brand: 'SALT WATER FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'KING FLY',
      slug: 'KING-FLY-SWATER-NAIRO',
      category: 'SALT WATER',
      image: '/images/130.jpg',
      price: 7.0,
      brand: 'SALT WATER FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'ORANGE TAIL TAPON',
      slug: 'ORANGE-TAIL-TAPON-SWATER-NAIRO',
      category: 'SALT WATER',
      image: '/images/131.jpg',
      price: 7.0,
      brand: 'SALT WATER FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'PINK ZONKER TAPON',
      slug: 'PINK-ZONKER-TAPON-SWATER-NAIRO',
      category: 'SALT WATER',
      image: '/images/132.jpg',
      price: 7.0,
      brand: 'SALT WATER FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'ORANGE ZONKER TAPON',
      slug: 'ORANGE-ZONKER-TAPON-SWATER-NAIRO',
      category: 'SALT WATER',
      image: '/images/133.jpg',
      price: 7.0,
      brand: 'SALT WATER FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'PURPLE ZONKER TAPON',
      slug: 'PURPLE-ZONKER-TAPON-SWATER-NAIRO',
      category: 'SALT WATER',
      image: '/images/134.jpg',
      price: 7.0,
      brand: 'SALT WATER FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'RED TAPON',
      slug: 'RED-TAPON-SWATER-NAIRO',
      category: 'SALT WATER',
      image: '/images/135.jpg',
      price: 7.0,
      brand: 'SALT WATER FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'WHITE TAPON',
      slug: 'WHITE-TAPON-SWATER-NAIRO',
      category: 'SALT WATER',
      image: '/images/136.jpg',
      price: 7.0,
      brand: 'SALT WATER FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'STRIPED STRIKER',
      slug: 'STRIPED-STRIKER-SWATER-NAIRO',
      category: 'SALT WATER',
      image: '/images/137.jpg',
      price: 7.0,
      brand: 'SALT WATER FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'BLACK DEATH',
      slug: 'BLACK-DEATH-SWATER-NAIRO',
      category: 'SALT WATER',
      image: '/images/138.jpg',
      price: 7.0,
      brand: 'SALT WATER FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'SHRIMP TAN',
      slug: 'SHRIMP-TAN-SWATER-NAIRO',
      category: 'SALT WATER',
      image: '/images/139.jpg',
      price: 7.0,
      brand: 'SALT WATER FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'TAPON SNAKE',
      slug: 'TAPON-SNAKE-SWATER-NAIRO',
      category: 'SALT WATER',
      image: '/images/140.jpg',
      price: 7.0,
      brand: 'SALT WATER FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'FLASHTAIL WHISTLER ',
      slug: 'FLASHTAIL-WHISTLER-SWATER-NAIRO',
      category: 'SALT WATER',
      image: '/images/141.jpg',
      price: 7.0,
      brand: 'SALT WATER FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'MINI PUFFS COLOR ORANGE',
      slug: 'MINI-PUFFS-COLOR-ORANGE-SWATER-NAIRO',
      category: 'SALT WATER',
      image: '/images/142.jpg',
      price: 7.0,
      brand: 'SALT WATER FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'KINKY MUDDLER',
      slug: 'KINKY-MUDDLER-SWATER-NAIRO',
      category: 'SALT WATER',
      image: '/images/143.jpg',
      price: 7.0,
      brand: 'SALT WATER FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'SNOOK FLY',
      slug: 'SNOOK-FLY-SWATER-NAIRO',
      category: 'SALT WATER',
      image: '/images/144.jpg',
      price: 7.0,
      brand: 'SALT WATER FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'CLOUSER MINNOW WHITE CHARTREUSE',
      slug: 'CLOUSER-MINNOW-WHITE-CHARTREUSE-SWATER-NAIRO',
      category: 'SALT WATER',
      image: '/images/145.jpg',
      price: 7.0,
      brand: 'SALT WATER FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'CREEPER BLUE',
      slug: 'CREEPER-BLUE-SWATER-NAIRO',
      category: 'SALT WATER',
      image: '/images/146.jpg',
      price: 7.0,
      brand: 'SALT WATER FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'DOUBLE EYE STRIKER',
      slug: 'DOUBLE-EYE-STRIKER-SWATER-NAIRO',
      category: 'SALT WATER',
      image: '/images/147.jpg',
      price: 7.0,
      brand: 'SALT WATER FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'CREAPER PEARLY',
      slug: 'CREAPER-PEARLY-SWATER-NAIRO',
      category: 'SALT WATER',
      image: '/images/148.jpg',
      price: 3,
      brand: 'SALT WATER FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
    {
      name: 'KUTCHERS FLY',
      slug: 'KUTCHERS-FLY-SWATER-NAIRO',
      category: 'SALT WATER',
      image: '/images/119.jpg',
      price: 7.0,
      brand: 'SALT WATER FLIES',
      rating: 9.5,
      numReviews: 10,
      countInStock: 1000,
      description: 'Hand made flies from Kenya',
    },
  ],
};

export default data;
